const sleep = ms => new Promise(r => setTimeout(r, ms));
const BASE = "http://127.0.0.1:4461";
const targets = await (await fetch("http://127.0.0.1:9333/json/list")).json();
let page = targets.find(t => t.type === "page");
const WebSocket = (await import("ws")).default;
const ws = new WebSocket(page.webSocketDebuggerUrl, { perMessageDeflate: false });
let id = 0; const pm = new Map();
const send = (m, p = {}) => new Promise((res, rej) => { const k = ++id; pm.set(k, { res, rej }); ws.send(JSON.stringify({ id: k, method: m, params: p })); });
const net = [];
ws.on("message", d => { const m = JSON.parse(d);
  if (m.id && pm.has(m.id)) { const c = pm.get(m.id); pm.delete(m.id); m.error ? c.rej(new Error(JSON.stringify(m.error))) : c.res(m.result); }
  if (m.method === "Network.requestWillBeSent" && m.params.request.method === "DELETE") net.push(m.params.request.url.slice(-30));
});
await new Promise(r => ws.on("open", r));
await send("Network.enable");
const evalv = async (expr) => { const v = await send("Runtime.evaluate", { expression: expr, returnByValue: true, awaitPromise: true }); return v.exceptionDetails ? "EXC:" + JSON.stringify(v.exceptionDetails.exception?.description || v.exceptionDetails).slice(0, 250) : v.result?.value; };
await evalv(`(() => { const t = document.querySelector('[data-feedback="retained"]'); if (t) t.click(); return 1; })()`);
await sleep(800);
await evalv(`(() => { window.__p = { captured: 0, delegated: 0 }; return 1; })()`);
await evalv(`(() => { document.getElementById('cards').addEventListener('click', () => window.__p.captured += 1, true); document.getElementById('cards').addEventListener('click', () => window.__p.delegated += 1, false); return 1; })()`);
const btn = await evalv(`(() => { const c = [...document.querySelectorAll('#cards .card')].find(x => x.querySelector('.c-kind.hl')); const b = [...c.querySelectorAll('button')].find(x => x.textContent === '取消保留'); const r = b.getBoundingClientRect(); return { x: r.left + r.width/2, y: r.top + r.height/2, hit: (() => { const el = document.elementFromPoint(r.left + r.width/2, r.top + r.height/2); return el === b ? 'SELF' : (el ? el.tagName + '.' + String(el.className).slice(0, 20) : 'out'); })() }; })()`);
console.log("按钮:", JSON.stringify(btn));
await send("Input.dispatchMouseEvent", { type: "mousePressed", x: Math.round(btn.x), y: Math.round(btn.y), button: "left", buttons: 1, clickCount: 1 });
await send("Input.dispatchMouseEvent", { type: "mouseReleased", x: Math.round(btn.x), y: Math.round(btn.y), button: "left", buttons: 0, clickCount: 1 });
await sleep(1500);
console.log("探针:", await evalv(`JSON.stringify(window.__p)`));
console.log("DELETE:", net.length ? net : "none");
console.log("剩余 active hl:", await evalv(`(async () => { const l = (await (await fetch('/api/annotations?p=' + encodeURIComponent('研究设计-技术附录.pdf'))).json()).annotations || []; return l.filter(a => a.kind === 'highlight' && a.status === 'active').length; })()`));
ws.close(); process.exit(0);
