const sleep = ms => new Promise(r => setTimeout(r, ms));
const BASE = "http://127.0.0.1:4461";
const targets = await (await fetch("http://127.0.0.1:9333/json/list")).json();
let page = targets.find(t => t.type === "page");
const WebSocket = (await import("ws")).default;
const ws = new WebSocket(page.webSocketDebuggerUrl, { perMessageDeflate: false });
let id = 0; const pm = new Map();
const send = (m, p = {}) => new Promise((res, rej) => { const k = ++id; pm.set(k, { res, rej }); ws.send(JSON.stringify({ id: k, method: m, params: p })); });
ws.on("message", d => { const m = JSON.parse(d); if (m.id && pm.has(m.id)) { const c = pm.get(m.id); pm.delete(m.id); m.error ? c.rej(new Error(JSON.stringify(m.error))) : c.res(m.result); } });
await new Promise(r => ws.on("open", r));
const evalv = async (expr) => { const v = await send("Runtime.evaluate", { expression: expr, returnByValue: true, awaitPromise: true }); return v.exceptionDetails ? "EXC:" + JSON.stringify(v.exceptionDetails.exception?.description || v.exceptionDetails).slice(0, 250) : v.result?.value; };
console.log("1+1:", await evalv(`1+1`));
console.log("filter:", await evalv(`document.querySelector('.feedback-tabs [aria-selected="true"]')?.dataset?.feedback`));
console.log("card 数:", await evalv(`document.querySelectorAll('#cards .card').length`));
console.log("retained tab 文本:", await evalv(`document.querySelector('[data-feedback="retained"]')?.textContent`));
await evalv(`(() => { const t = document.querySelector('[data-feedback="retained"]'); if (t) t.click(); return 1; })()`);
await sleep(800);
console.log("切 retained 后 card 数:", await evalv(`document.querySelectorAll('#cards .card').length`));
console.log("保留卡按钮:", await evalv(`(() => { const c = [...document.querySelectorAll('#cards .card')].find(x => x.querySelector('.c-kind.hl')); return c ? JSON.stringify([...c.querySelectorAll('button')].map(x => x.textContent)) : 'no-hl-card'; })()`));
ws.close(); process.exit(0);
